export { default as AddProduct } from "./AddProduct"
export { default as Product } from "./Product"
export { default as Recap } from "./Recap"
export { default as Header } from "./Header"
export { default as Footer } from "./Footer"
